#!/bin/sh

#
# $Id$
#

#
# Build all add-on packages for the current RTEMS_MAKEFILE_PATH architecture.
#
set -ex

PACKAGES="avl-1.4.0 gsl-1.9 ncurses-5.9 readline-6.2 libtecla-1.6.1"

# make sure it is clean before we start
#for p in $PACKAGES
#do
#	(cd $p ; make clean distclean || true)
#done

for p in $PACKAGES
do
    cd $p
    makefile="../RTEMS_Makefiles/Makefile.$p"
    if [ \! -r "$makefile" ]
    then
        makefile="`echo $makefile | sed -e '/-.*/s///'`"
    fi
    if [ -r "$makefile" ]
    then
        make -w -f "$makefile"
    else
        make -w 
        make -w install
    fi
    cd ..
done

for p in $PACKAGES
do
	(cd $p ; make clean distclean || true)
done
