#!/bin/sh

#
# Build all add-on packages for the current RTEMS_MAKEFILE_PATH architecture.
#
set -ex

PACKAGES="avl-1.4.0 ncurses-5.2 readline-4.3"

for p in $PACKAGES
do
	(
        cd $p
        makefile="../RTEMS_Makefiles/Makefile.$p"
        if [ \! -r "$makefile" ]
        then
            makefile="`echo $makefile | sed -e '/-.*/s///'`"
        fi
        make -f "$makefile"
    )
done

for p in $PACKAGES
do
	(cd $p ; make distclean)
done
