include ../RTEMS_Makefiles/Makefile.common

all:
	./configure \
		--host=`uname -m`-$(RTEMS_HOST) \
		--prefix=$(exec_prefix) \
		--libdir=$(exec_prefix)/$(RTEMS_BSP)/lib \
		--includedir=$(exec_prefix)/$(RTEMS_BSP)/lib/include
	make
	make install
