#
# Configure/build/install the AVL library
#
include ../RTEMS_Makefiles/Makefile.common

AR = $(AR_FOR_TARGET) cr
all:
	./configure \
		--prefix=$(exec_prefix) \
		--libdir=$(exec_prefix)/$(RTEMS_BSP)/lib \
		--includedir=$(exec_prefix)/$(RTEMS_BSP)/lib/include
	make 
	make install
